apiVersion: v1
kind: Pod
metadata:
  name: nginx-debug
  namespace: devops
  annotations:
    injector.tumblr.com/request: sidecar-debian
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: IfNotPresent
    name: nginx-debug
  restartPolicy: Never
