apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: "k8s-sidecar-injector-webhook"
  labels:
    app: devops-sidecar-injector
    track: sandbox
webhooks:
- name: "injector.tumblr.com"
  failurePolicy: "Ignore" # we fail "open" if the webhook is down hard
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  clientConfig:
    service:
      name: "devops-sidecar-injector-sandbox"
      namespace: "devops"
      path: "/mutate"   # what /url/slug to send requests at
    caBundle: "__CA_BUNDLE_BASE64__"
