apiVersion: v1
kind: Service
metadata:
  name: devops-sidecar-injector-sandbox
  namespace: devops
  labels:
    devops-app: devops-sidecar-injector
    track: sandbox
spec:
  type: ClusterIP # NOTE: because of how MutatingWebhookConfigurations work, we MUST set this to have a clusterip
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  - name: http-metrics
    port: 80
    targetPort: http-metrics
    protocol: TCP
  selector:
    devops-app: devops-sidecar-injector
    track: sandbox
